production:
 url: <%= ENV['DATABASE_URL'] %>

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost

development:
  <<: *default
  database: coder-pinterest_development

test:
  <<: *default
  database: coder-pinterest_test
