production:
 url: <%= ENV['DATABASE_URL'] %>

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: coder-pinterest_development
  username: postgres
  password: password
  host: localhost
  
test:
  <<: *default
  database: coder-pinterest_test
  username: postgres
  password: password
  host: localhost
